# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run E2E tests
        uses: cypress-io/github-action@v4.1.0
        with:
          start: npm run dev
          wait-on: 'http://localhost:3000'

      - name: Run Component tests
        uses: cypress-io/github-action@v4.1.0
        with:
          install: false
          component: true