# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3.0
        with:
          envkey_VITE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          envkey_VITE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN}}
          envkey_VITE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          envkey_VITE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET}}
          envkey_VITE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          envkey_VITE_APP_ID: ${{ secrets.FIREBASE_APP_ID}}
          envkey_VITE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
      - name: Run E2E tests
        uses: cypress-io/github-action@v4.1.0
        with:
          start: npm run dev
          wait-on: 'http://localhost:3000'

      - name: Run Component tests
        uses: cypress-io/github-action@v4.1.0
        with:
          install: false
          component: true